# Site settings
title: Developing Benny
header-img: img/home-bg.png
email: bennybop74@yahoo.com
copyright_name: bennybop
description: > # this means to ignore newlines until "baseurl:"
  Software developer in training
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  bennybop
learn_profile: bennybop
email_username: bennybop74@yahoo.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
